In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./preprocessed.csv')

In [3]:
df.head()

,Unnamed: 0,answer_count,average_answer_length,total_votes_given_answers,total_votes_received_answers,question_count,average_question_length,total_votes_given_questions,total_votes_received_questions,total_questions_following,...,country_cd_SZ,country_cd_TH,country_cd_UA,country_cd_US,country_cd_VG,country_cd_VI,country_cd_ZA,reported_or_inferred_gender_female,reported_or_inferred_gender_male,completed
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2,0.243902,0.452514,0.000000,0.000000,0.000000,0.452514,0.0,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,3,0.121951,0.334333,0.024390,0.083333,0.011628,0.334333,0.0,0.266667,0.333333,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
4,4,0.268293,0.170753,0.073171,0.250000,0.000000,0.170753,0.0,0.200000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.columns

Index(['answer_count', 'average_answer_length', 'total_votes_given_answers',
       'total_votes_received_answers', 'question_count',
       'average_question_length', 'total_votes_given_questions',
       'total_votes_received_questions', 'total_questions_following',
       'country_cd_AE', 'country_cd_AG', 'country_cd_AT', 'country_cd_AU',
       'country_cd_BD', 'country_cd_BE', 'country_cd_CA', 'country_cd_CN',
       'country_cd_FR', 'country_cd_GB', 'country_cd_GR', 'country_cd_GT',
       'country_cd_GY', 'country_cd_HK', 'country_cd_ID', 'country_cd_IL',
       'country_cd_IN', 'country_cd_IQ', 'country_cd_IT', 'country_cd_JO',
       'country_cd_JP', 'country_cd_KR', 'country_cd_KW', 'country_cd_KY',
       'country_cd_LC', 'country_cd_MX', 'country_cd_NG', 'country_cd_NL',
       'country_cd_NZ', 'country_cd_OM', 'country_cd_PK', 'country_cd_PL',
       'country_cd_PT', 'country_cd_PY', 'country_cd_SG', 'country_cd_SL',
       'country_cd_SX', 'country_cd_SZ', 'country_cd_TH', 'country_cd_UA',
       'country_cd_US', 'country_cd_VG', 'country_cd_VI', 'country_cd_ZA',
       'reported_or_inferred_gender_female',
       'reported_or_inferred_gender_male', 'completed'],
      dtype='object')

In [6]:
protected = ['country_cd_AE', 'country_cd_AG', 'country_cd_AT', 'country_cd_AU',
       'country_cd_BD', 'country_cd_BE', 'country_cd_CA', 'country_cd_CN',
       'country_cd_FR', 'country_cd_GB', 'country_cd_GR', 'country_cd_GT',
       'country_cd_GY', 'country_cd_HK', 'country_cd_ID', 'country_cd_IL',
       'country_cd_IN', 'country_cd_IQ', 'country_cd_IT', 'country_cd_JO',
       'country_cd_JP', 'country_cd_KR', 'country_cd_KW', 'country_cd_KY',
       'country_cd_LC', 'country_cd_MX', 'country_cd_NG', 'country_cd_NL',
       'country_cd_NZ', 'country_cd_OM', 'country_cd_PK', 'country_cd_PL',
       'country_cd_PT', 'country_cd_PY', 'country_cd_SG', 'country_cd_SL',
       'country_cd_SX', 'country_cd_SZ', 'country_cd_TH', 'country_cd_UA',
       'country_cd_US', 'country_cd_VG', 'country_cd_VI', 'country_cd_ZA',
       'reported_or_inferred_gender_female',
       'reported_or_inferred_gender_male']

In [7]:
all = df.columns

In [8]:
new_df = pd.DataFrame(0, columns=all, index=df.index)

In [9]:
new_df[protected] = 1

In [10]:
new_df.head()

,answer_count,average_answer_length,total_votes_given_answers,total_votes_received_answers,question_count,average_question_length,total_votes_given_questions,total_votes_received_questions,total_questions_following,country_cd_AE,...,country_cd_SZ,country_cd_TH,country_cd_UA,country_cd_US,country_cd_VG,country_cd_VI,country_cd_ZA,reported_or_inferred_gender_female,reported_or_inferred_gender_male,completed
0,0,0,0,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,0
1,0,0,0,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,0
2,0,0,0,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,0
3,0,0,0,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,0
4,0,0,0,0,0,0,0,0,0,1,...,1,1,1,1,1,1,1,1,1,0

In [ ]:
new_df['completed'] = 2

In [11]:
new_df.to_csv('protected.csv', index=False)